services:
  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nurgame_db
    ports:
      - 5432:5432
  app:
    image: my-node-app
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: nurgame_db
      DB_HOST: db
      DB_PORT: 5432
    ports: 
      - 13000:4001
    depends_on:
      - db
networks:
  default:
    driver: bridge